# Generated by Django 5.2 on 2025-04-13 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labresult',
            options={'ordering': ['-result_date']},
        ),
        migrations.RemoveField(
            model_name='labresult',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='labresult',
            name='ordering_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_lab_results', to='emr.doctor'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='emr.patient'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='performing_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_lab_results', to='emr.doctor'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['patient'], name='emr_labresu_patient_3c2af0_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['ordering_doctor'], name='emr_labresu_orderin_f12544_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['performing_doctor'], name='emr_labresu_perform_96410e_idx'),
        ),
    ]
